import type {
  PointsActivityType,
  PointsRuleConfig,
  RuntimeShopItem,
  ShirtLevel,
  TierLevel,
} from "@/lib/points/types";

export const DEFAULT_POINTS_RULE_CONFIG: PointsRuleConfig = {
  xpToCreditsPct: 40,
  weeklyNonSessionCap: 25,
  freezeNonSessionWithoutMonthlySession: true,
  shirtThresholdMultiplier: 1,
  shopPriceMultiplier: 1,
};

export const MAX_SESSIONS_PER_WEEK = 2;

export const SESSION_ACTIVITY_TYPES: PointsActivityType[] = [
  "private_session",
  "group_session",
  "online_film_session",
];

export const ACTIVITY_BASE_XP: Record<PointsActivityType, number> = {
  private_session: 20,
  group_session: 12,
  online_film_session: 20,
  watch_assigned_video: 3,
  upload_video_review: 4,
  coach_set_goal: 15,
  beat_test_minor: 1,
  beat_test_clear: 3,
  beat_major_benchmark: 5,
  complete_task: 2,
  reach_self_set_goal: 0,
  repeat_same_goal: 0,
};

export const SHIRT_LEVELS: ShirtLevel[] = [
  { name: "No Shirt", minXp: 0, maxXp: 59, rank: 1 },
  { name: "Black", minXp: 60, maxXp: 454, rank: 2 },
  { name: "White", minXp: 455, maxXp: 844, rank: 3 },
  { name: "Green", minXp: 845, maxXp: 1689, rank: 4 },
  { name: "Navy", minXp: 1690, maxXp: 2664, rank: 5 },
  { name: "Indigo", minXp: 2665, maxXp: 4354, rank: 6 },
  { name: "Red", minXp: 4355, maxXp: null, rank: 7 },
];

export const TIER_LEVELS: TierLevel[] = [
  { name: "Igniter", minXp: 0, maxXp: 59, rank: 1 },
  { name: "Builder", minXp: 60, maxXp: 454, rank: 2 },
  { name: "Grinder", minXp: 455, maxXp: 844, rank: 3 },
  { name: "Playmaker", minXp: 845, maxXp: 1689, rank: 4 },
  { name: "Captain", minXp: 1690, maxXp: 2664, rank: 5 },
  { name: "Icon", minXp: 2665, maxXp: 4354, rank: 6 },
  { name: "Legend", minXp: 4355, maxXp: null, rank: 7 },
];

export const DISCOUNT_SHIRT_MONTHLY_CAP: Record<string, number> = {
  Green: 1,
  Navy: 2,
  Indigo: 3,
  Red: 4,
};

export const RUNTIME_SHOP_ITEMS: RuntimeShopItem[] = [
  {
    id: 1,
    itemKey: "mini-cones-pack",
    name: "Mini Cones Pack",
    category: "Equipment",
    rarity: "Common",
    description: "Compact cone set for first-touch drills.",
    priceCredits: 95,
    unlockShirt: "Black",
    itemType: "physical",
    baseRepeatLimit: 2,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 10,
  },
  {
    id: 2,
    itemKey: "flat-marker-cones",
    name: "Flat Marker Cones",
    category: "Equipment",
    rarity: "Common",
    description: "Low-profile marker cones for dribbling lanes.",
    priceCredits: 105,
    unlockShirt: "Black",
    itemType: "physical",
    baseRepeatLimit: 2,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 11,
  },
  {
    id: 3,
    itemKey: "tall-speed-cones",
    name: "Tall Speed Cones",
    category: "Equipment",
    rarity: "Uncommon",
    description: "Tall cones for slalom speed progression.",
    priceCredits: 120,
    unlockShirt: "Black",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 12,
  },
  {
    id: 4,
    itemKey: "agility-pole-set",
    name: "Agility Pole Set",
    category: "Equipment",
    rarity: "Uncommon",
    description: "Portable agility poles for pattern work.",
    priceCredits: 135,
    unlockShirt: "Black",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 13,
  },
  {
    id: 5,
    itemKey: "speed-rings-kit",
    name: "Speed Rings Kit",
    category: "Equipment",
    rarity: "Uncommon",
    description: "Multi-ring kit for explosive footwork.",
    priceCredits: 145,
    unlockShirt: "Black",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 14,
  },
  {
    id: 6,
    itemKey: "reaction-ball",
    name: "Reaction Ball",
    category: "Equipment",
    rarity: "Uncommon",
    description: "Unpredictable bounce trainer for reaction speed.",
    priceCredits: 160,
    unlockShirt: "Black",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 15,
  },
  {
    id: 7,
    itemKey: "dst-ball-pump-kit",
    name: "DST Ball Pump Kit",
    category: "Equipment",
    rarity: "Rare",
    description: "Pump kit with pressure gauge and adapters.",
    priceCredits: 175,
    unlockShirt: "Black",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 16,
  },
  {
    id: 8,
    itemKey: "first-touch-wall-straps",
    name: "First Touch Wall Straps",
    category: "Equipment",
    rarity: "Rare",
    description: "Strap kit for repeat first-touch reps.",
    priceCredits: 210,
    unlockShirt: "Black",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 17,
  },
  {
    id: 9,
    itemKey: "pro-agility-ladder",
    name: "Pro Agility Ladder",
    category: "Equipment",
    rarity: "Uncommon",
    description: "Durable ladder for advanced movement patterns.",
    priceCredits: 180,
    unlockShirt: "White",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 30,
  },
  {
    id: 10,
    itemKey: "heavy-flat-cone-bundle",
    name: "Heavy Flat Cone Bundle",
    category: "Equipment",
    rarity: "Uncommon",
    description: "Wind-resistant flat cone bundle.",
    priceCredits: 195,
    unlockShirt: "White",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 31,
  },
  {
    id: 11,
    itemKey: "resistance-band-training-set",
    name: "Resistance Band Training Set",
    category: "Equipment",
    rarity: "Uncommon",
    description: "Progressive resistance bands for power and balance.",
    priceCredits: 210,
    unlockShirt: "White",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 32,
  },
  {
    id: 12,
    itemKey: "precision-passing-gates",
    name: "Precision Passing Gates",
    category: "Equipment",
    rarity: "Rare",
    description: "Gate targets for passing accuracy challenges.",
    priceCredits: 230,
    unlockShirt: "White",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 33,
  },
  {
    id: 13,
    itemKey: "dst-compression-tee",
    name: "DST Compression Tee",
    category: "Brand Apparel",
    rarity: "Rare",
    description: "Training compression top with DST crest.",
    priceCredits: 255,
    unlockShirt: "White",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 34,
  },
  {
    id: 14,
    itemKey: "dst-training-shorts",
    name: "DST Training Shorts",
    category: "Brand Apparel",
    rarity: "Rare",
    description: "Breathable shorts built for high-load sessions.",
    priceCredits: 275,
    unlockShirt: "White",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 35,
  },
  {
    id: 15,
    itemKey: "elite-shin-guard-set",
    name: "Elite Shin Guard Set",
    category: "Equipment",
    rarity: "Epic",
    description: "Premium shin guards with reinforced shell.",
    priceCredits: 310,
    unlockShirt: "White",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 36,
  },
  {
    id: 16,
    itemKey: "dst-player-backpack",
    name: "DST Player Backpack",
    category: "Brand Apparel",
    rarity: "Epic",
    description: "Large player backpack with cleat compartment.",
    priceCredits: 340,
    unlockShirt: "White",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 37,
  },
  {
    id: 17,
    itemKey: "group-session-15-off",
    name: "Group Session 15% Off",
    category: "Discount",
    rarity: "Rare",
    description: "Apply 15% off one group session booking.",
    priceCredits: 260,
    unlockShirt: "Green",
    itemType: "discount",
    baseRepeatLimit: null,
    monthlyCap: 1,
    repeatScalesWithTier: false,
    sortOrder: 50,
  },
  {
    id: 18,
    itemKey: "private-session-10-off",
    name: "Private Session 10% Off",
    category: "Discount",
    rarity: "Rare",
    description: "Apply 10% off one private session booking.",
    priceCredits: 320,
    unlockShirt: "Green",
    itemType: "discount",
    baseRepeatLimit: null,
    monthlyCap: 1,
    repeatScalesWithTier: false,
    sortOrder: 51,
  },
  {
    id: 19,
    itemKey: "smart-ball-sensor-sleeve",
    name: "Smart Ball Sensor Sleeve",
    category: "Equipment",
    rarity: "Epic",
    description: "Sensor sleeve for touch-count tracking.",
    priceCredits: 360,
    unlockShirt: "Green",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 52,
  },
  {
    id: 20,
    itemKey: "custom-dst-name-tee",
    name: "Custom DST Name Tee",
    category: "Brand Apparel",
    rarity: "Epic",
    description: "Custom-printed DST training tee.",
    priceCredits: 340,
    unlockShirt: "Green",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: false,
    sortOrder: 53,
  },
  {
    id: 21,
    itemKey: "group-session-25-off",
    name: "Group Session 25% Off",
    category: "Discount",
    rarity: "Epic",
    description: "Apply 25% off one group session booking.",
    priceCredits: 430,
    unlockShirt: "Navy",
    itemType: "discount",
    baseRepeatLimit: null,
    monthlyCap: 2,
    repeatScalesWithTier: false,
    sortOrder: 70,
  },
  {
    id: 22,
    itemKey: "private-session-20-off",
    name: "Private Session 20% Off",
    category: "Discount",
    rarity: "Epic",
    description: "Apply 20% off one private session booking.",
    priceCredits: 520,
    unlockShirt: "Navy",
    itemType: "discount",
    baseRepeatLimit: null,
    monthlyCap: 2,
    repeatScalesWithTier: false,
    sortOrder: 71,
  },
  {
    id: 23,
    itemKey: "elite-recovery-kit",
    name: "Elite Recovery Kit",
    category: "Equipment",
    rarity: "Epic",
    description: "Recovery bundle: roller, bands, and mobility tools.",
    priceCredits: 480,
    unlockShirt: "Navy",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 72,
  },
  {
    id: 24,
    itemKey: "advanced-dribble-mannequin-pair",
    name: "Advanced Dribble Mannequin Pair",
    category: "Equipment",
    rarity: "Legendary",
    description: "Two mannequins for directional dribbling setups.",
    priceCredits: 550,
    unlockShirt: "Navy",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: true,
    sortOrder: 73,
  },
  {
    id: 25,
    itemKey: "group-session-35-off",
    name: "Group Session 35% Off",
    category: "Discount",
    rarity: "Legendary",
    description: "Apply 35% off one group session booking.",
    priceCredits: 590,
    unlockShirt: "Indigo",
    itemType: "discount",
    baseRepeatLimit: null,
    monthlyCap: 3,
    repeatScalesWithTier: false,
    sortOrder: 90,
  },
  {
    id: 26,
    itemKey: "private-session-30-off",
    name: "Private Session 30% Off",
    category: "Discount",
    rarity: "Legendary",
    description: "Apply 30% off one private session booking.",
    priceCredits: 700,
    unlockShirt: "Indigo",
    itemType: "discount",
    baseRepeatLimit: null,
    monthlyCap: 3,
    repeatScalesWithTier: false,
    sortOrder: 91,
  },
  {
    id: 27,
    itemKey: "pro-film-review-bundle",
    name: "Pro Film Review Bundle",
    category: "Discount",
    rarity: "Legendary",
    description: "Discounted advanced film review package.",
    priceCredits: 620,
    unlockShirt: "Indigo",
    itemType: "discount",
    baseRepeatLimit: null,
    monthlyCap: 3,
    repeatScalesWithTier: false,
    sortOrder: 92,
  },
  {
    id: 28,
    itemKey: "dst-pro-player-kit",
    name: "DST Pro Player Kit",
    category: "Brand Apparel",
    rarity: "Legendary",
    description: "Premium DST training apparel kit.",
    priceCredits: 760,
    unlockShirt: "Indigo",
    itemType: "physical",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: false,
    sortOrder: 93,
  },
  {
    id: 29,
    itemKey: "priority-booking-token-30-days",
    name: "Priority Booking Token (30 days)",
    category: "VIP",
    rarity: "Legendary",
    description: "Priority booking window for 30 days.",
    priceCredits: 850,
    unlockShirt: "Red",
    itemType: "vip",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: false,
    sortOrder: 110,
  },
  {
    id: 30,
    itemKey: "vip-masterclass-seat",
    name: "VIP Masterclass Seat",
    category: "VIP",
    rarity: "Legendary",
    description: "Guaranteed seat in limited masterclass event.",
    priceCredits: 900,
    unlockShirt: "Red",
    itemType: "vip",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: false,
    sortOrder: 111,
  },
  {
    id: 31,
    itemKey: "elite-camp-vip-pass",
    name: "Elite Camp VIP Pass",
    category: "VIP",
    rarity: "Mythic",
    description: "Top-tier VIP pass for DST elite camp access.",
    priceCredits: 1200,
    unlockShirt: "Red",
    itemType: "vip",
    baseRepeatLimit: 1,
    monthlyCap: null,
    repeatScalesWithTier: false,
    sortOrder: 112,
  },
];

export const SHOP_ITEMS_BY_ID = new Map<number, RuntimeShopItem>(
  RUNTIME_SHOP_ITEMS.map((item) => [item.id, item]),
);

export const SHOP_ITEMS_BY_KEY = new Map<string, RuntimeShopItem>(
  RUNTIME_SHOP_ITEMS.map((item) => [item.itemKey, item]),
);
